name: ${REPO}
services:
    app:
        image: ${IMAGE}
        container_name: portfolio-website
        restart: always
        networks:
            - traefik-public
        labels:
            - traefik.enable=true
            - traefik.http.routers.portfolio.rule=Host(`aarcot.com`)
            - traefik.http.routers.portfolio.entrypoints=websecure
            - traefik.http.routers.portfolio.tls=true
            - traefik.http.routers.portfolio.tls.certresolver=le

networks:
    traefik-public:
        external: true
