name: portfolio

services:
    app:
        image: ${IMAGE?}
        container_name: portfolio
        restart: always
        networks:
            - traefik-public
        labels:
            - traefik.enable=true
            - traefik.http.routers.portfolio.rule=Host(`aarcot.com`) || Host(`www.aarcot.com`)
            - traefik.http.routers.portfolio.entrypoints=websecure

networks:
    traefik-public:
        external: true
